spring.application.name=api-monitoring

server.port=80
server.servlet.context-path=/monitoring

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/monitoring_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRESQL_PASSWORD}

rsa.public-key=classpath:secrets/public.pem
rsa.private-key=classpath:secrets/private.pem

#logging.level.org.springframework.security=TRACE